export const enum ORDER_TYPES {
  ARRIVAL_NOTICE = 'ARRIVAL_NOTICE',
  SHIPPING = 'SHIPPING_ORDER',
  DELIVERY = 'DELIVERY',
  COLLECTION = 'COLLECTION',
  RELEASE_OF_GOODS = 'RELEASE_OF_GOODS'
}

export const enum ORDER_STATUS {
  PENDING = 'PENDING',
  EDITING = 'EDITING',
  PENDING_RECEIVE = 'PENDING_RECEIVE',
  INTRANSIT = 'INTRANSIT',
  ARRIVED = 'ARRIVED',
  READY_TO_UNLOAD = 'READY_TO_UNLOAD',
  READY_TO_PUTAWAY = 'READY_TO_PUTAWAY',
  PROCESSING = 'PROCESSING',
  DONE = 'DONE'
}

export const enum ORDER_PRODUCT_STATUS {
  PENDING = 'PENDING',
  INTRANSIT = 'INTRANSIT',
  ARRIVED = 'ARRIVED',
  READY_TO_UNLOAD = 'READY_TO_UNLOAD',
  UNLOADING = 'UNLOADING',
  UNLOADED = 'UNLOADED',
  READY_TO_PUTAWAY = 'READY_TO_PUTAWAY',
  PUTTING_AWAY = 'PUTTING_AWAY',
  STORED = 'STORED'
}

export const enum ORDER_VAS_STATUS {
  PENDING = 'PENDING',
  READY_TO_PROCESS = 'READY_TO_PROCESS',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  UNCOMPLETED = 'UNCOMPLETED'
}
