export const enum WORKSHEET_TYPE {
  ARRIVAL_NOTICE = 'ARRIVAL_NOTICE',
  UNLOADING = 'UNLOADING',
  PUTAWAY = 'PUTAWAY',
  VAS = 'VAS',
  LOADING = 'LOADING',
  PICKING = 'PICKING'
}

export const enum WORKSHEET_STATUS {
  DEACTIVATED = 'DEACTIVATED',
  EXECUTING = 'EXECUTING',
  DONE = 'DONE'
}
