export const TEMPLATE_TYPE = {
  DO_TEMPLATE: 'DO_TEMPLATE',
  CO_TEMPLATE: 'CO_TEMPLATE',
  GRN_TEMPLATE: 'GRN_TEMPLATE',
  JOB_TEMPLATE: 'JOB_TEMPLATE',
  COP: 'COP',
  SIGNATURE: 'SIGNATURE',
  LOGO: 'LOGO'
}
