export const TRANSACTION_TYPE = {
  UNLOADING: 'UNLOADING',
  PUTAWAY: 'PUTAWAY',
  ADJUSTMENT: 'ADJUSTMENT',
  PICKING: 'PICKING',
  LOADING: 'LOADING',
  RETURN: 'RETURN',
  TERMINATED: 'TERMINATED'
}
