export const WORKSHEET_TYPE = {
  UNLOADING: 'UNLOADING',
  PUTAWAY: 'PUTAWAY',
  VAS: 'VAS',
  PICKING: 'PICKING',
  LOADING: 'LOADING',
  CYCLE_COUNT: 'CYCLE_COUNT',
  RETURN: 'RETURN'
}

export const WORKSHEET_STATUS = {
  DEACTIVATED: 'DEACTIVATED',
  EXECUTING: 'EXECUTING',
  NOT_TALLY: 'NOT_TALLY',
  PARTIALLY_UNLOADED: 'PARTIALLY_UNLOADED',
  DONE: 'DONE',
  REPLACED: 'REPLACED'
}
